[package]
name = "lsm_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippy-utilities = "0.1.0"
anyhow = "1"
bytes = "1"
moka = "0.9"
log = "0.4"
rand = "0.8.5"